import { Injectable } from '@angular/core';
import { BibleBook } from '../../models/bible.models';

@Injectable({ providedIn: 'root' })
export class BibleDataService {
  readonly books: BibleBook[] = [
    { id: 'gen', name: 'Gênesis', testament: 'Antigo', chapters: 50, abbreviation: 'Gn' },
    { id: 'exo', name: 'Êxodo', testament: 'Antigo', chapters: 40, abbreviation: 'Êx' },
    { id: 'lev', name: 'Levítico', testament: 'Antigo', chapters: 27, abbreviation: 'Lv' },
    { id: 'num', name: 'Números', testament: 'Antigo', chapters: 36, abbreviation: 'Nm' },
    { id: 'deu', name: 'Deuteronômio', testament: 'Antigo', chapters: 34, abbreviation: 'Dt' },
    { id: 'jos', name: 'Josué', testament: 'Antigo', chapters: 24, abbreviation: 'Js' },
    { id: 'jdg', name: 'Juízes', testament: 'Antigo', chapters: 21, abbreviation: 'Jz' },
    { id: 'rut', name: 'Rute', testament: 'Antigo', chapters: 4, abbreviation: 'Rt' },
    { id: '1sa', name: '1 Samuel', testament: 'Antigo', chapters: 31, abbreviation: '1Sm' },
    { id: '2sa', name: '2 Samuel', testament: 'Antigo', chapters: 24, abbreviation: '2Sm' },
    { id: '1ki', name: '1 Reis', testament: 'Antigo', chapters: 22, abbreviation: '1Rs' },
    { id: '2ki', name: '2 Reis', testament: 'Antigo', chapters: 25, abbreviation: '2Rs' },
    { id: '1ch', name: '1 Crônicas', testament: 'Antigo', chapters: 29, abbreviation: '1Cr' },
    { id: '2ch', name: '2 Crônicas', testament: 'Antigo', chapters: 36, abbreviation: '2Cr' },
    { id: 'ezr', name: 'Esdras', testament: 'Antigo', chapters: 10, abbreviation: 'Ed' },
    { id: 'neh', name: 'Neemias', testament: 'Antigo', chapters: 13, abbreviation: 'Ne' },
    { id: 'est', name: 'Ester', testament: 'Antigo', chapters: 10, abbreviation: 'Et' },
    { id: 'job', name: 'Jó', testament: 'Antigo', chapters: 42, abbreviation: 'Jó' },
    { id: 'ps', name: 'Salmos', testament: 'Antigo', chapters: 150, abbreviation: 'Sl' },
    { id: 'pro', name: 'Provérbios', testament: 'Antigo', chapters: 31, abbreviation: 'Pv' },
    { id: 'ecc', name: 'Eclesiastes', testament: 'Antigo', chapters: 12, abbreviation: 'Ec' },
    { id: 'cant', name: 'Cânticos', testament: 'Antigo', chapters: 8, abbreviation: 'Ct' },
    { id: 'isa', name: 'Isaías', testament: 'Antigo', chapters: 66, abbreviation: 'Is' },
    { id: 'jer', name: 'Jeremias', testament: 'Antigo', chapters: 52, abbreviation: 'Jr' },
    { id: 'lam', name: 'Lamentações', testament: 'Antigo', chapters: 5, abbreviation: 'Lm' },
    { id: 'eze', name: 'Ezequiel', testament: 'Antigo', chapters: 48, abbreviation: 'Ez' },
    { id: 'dan', name: 'Daniel', testament: 'Antigo', chapters: 12, abbreviation: 'Dn' },
    { id: 'hos', name: 'Oséias', testament: 'Antigo', chapters: 14, abbreviation: 'Os' },
    { id: 'joe', name: 'Joel', testament: 'Antigo', chapters: 3, abbreviation: 'Jl' },
    { id: 'amo', name: 'Amós', testament: 'Antigo', chapters: 9, abbreviation: 'Am' },
    { id: 'oba', name: 'Obadias', testament: 'Antigo', chapters: 1, abbreviation: 'Ob' },
    { id: 'jon', name: 'Jonas', testament: 'Antigo', chapters: 4, abbreviation: 'Jn' },
    { id: 'mic', name: 'Miquéias', testament: 'Antigo', chapters: 7, abbreviation: 'Mq' },
    { id: 'nah', name: 'Naum', testament: 'Antigo', chapters: 3, abbreviation: 'Na' },
    { id: 'hab', name: 'Habacuque', testament: 'Antigo', chapters: 3, abbreviation: 'Hc' },
    { id: 'zep', name: 'Sofonias', testament: 'Antigo', chapters: 3, abbreviation: 'Sf' },
    { id: 'hag', name: 'Ageu', testament: 'Antigo', chapters: 2, abbreviation: 'Ag' },
    { id: 'zec', name: 'Zacarias', testament: 'Antigo', chapters: 14, abbreviation: 'Zc' },
    { id: 'mal', name: 'Malaquias', testament: 'Antigo', chapters: 4, abbreviation: 'Ml' },
    { id: 'mat', name: 'Mateus', testament: 'Novo', chapters: 28, abbreviation: 'Mt' },
    { id: 'mar', name: 'Marcos', testament: 'Novo', chapters: 16, abbreviation: 'Mc' },
    { id: 'luk', name: 'Lucas', testament: 'Novo', chapters: 24, abbreviation: 'Lc' },
    { id: 'joh', name: 'João', testament: 'Novo', chapters: 21, abbreviation: 'Jo' },
    { id: 'act', name: 'Atos', testament: 'Novo', chapters: 28, abbreviation: 'At' },
    { id: 'rom', name: 'Romanos', testament: 'Novo', chapters: 16, abbreviation: 'Rm' },
    { id: '1co', name: '1 Coríntios', testament: 'Novo', chapters: 16, abbreviation: '1Co' },
    { id: '2co', name: '2 Coríntios', testament: 'Novo', chapters: 13, abbreviation: '2Co' },
    { id: 'gal', name: 'Gálatas', testament: 'Novo', chapters: 6, abbreviation: 'Gl' },
    { id: 'eph', name: 'Efésios', testament: 'Novo', chapters: 6, abbreviation: 'Ef' },
    { id: 'php', name: 'Filipenses', testament: 'Novo', chapters: 4, abbreviation: 'Fp' },
    { id: 'col', name: 'Colossenses', testament: 'Novo', chapters: 4, abbreviation: 'Cl' },
    { id: '1th', name: '1 Tessalonicenses', testament: 'Novo', chapters: 5, abbreviation: '1Ts' },
    { id: '2th', name: '2 Tessalonicenses', testament: 'Novo', chapters: 3, abbreviation: '2Ts' },
    { id: '1ti', name: '1 Timóteo', testament: 'Novo', chapters: 6, abbreviation: '1Tm' },
    { id: '2ti', name: '2 Timóteo', testament: 'Novo', chapters: 4, abbreviation: '2Tm' },
    { id: 'tit', name: 'Tito', testament: 'Novo', chapters: 3, abbreviation: 'Tt' },
    { id: 'phm', name: 'Filemom', testament: 'Novo', chapters: 1, abbreviation: 'Fm' },
    { id: 'heb', name: 'Hebreus', testament: 'Novo', chapters: 13, abbreviation: 'Hb' },
    { id: 'jas', name: 'Tiago', testament: 'Novo', chapters: 5, abbreviation: 'Tg' },
    { id: '1pe', name: '1 Pedro', testament: 'Novo', chapters: 5, abbreviation: '1Pe' },
    { id: '2pe', name: '2 Pedro', testament: 'Novo', chapters: 3, abbreviation: '2Pe' },
    { id: '1jn', name: '1 João', testament: 'Novo', chapters: 5, abbreviation: '1Jo' },
    { id: '2jn', name: '2 João', testament: 'Novo', chapters: 1, abbreviation: '2Jo' },
    { id: '3jn', name: '3 João', testament: 'Novo', chapters: 1, abbreviation: '3Jo' },
    { id: 'jud', name: 'Judas', testament: 'Novo', chapters: 1, abbreviation: 'Jd' },
    { id: 'rev', name: 'Apocalipse', testament: 'Novo', chapters: 22, abbreviation: 'Ap' }
  ];

  getBookById(id: string): BibleBook | undefined {
    return this.books.find((book) => book.id === id);
  }
}
